// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp8HlPZyyzh6-hMXQgGkhB1rb4U6pJ7YE',
    appId: '1:313669347193:web:b1e62d0053a6e7aeac31a8',
    messagingSenderId: '313669347193',
    projectId: 'reddit-clone-bf910',
    authDomain: 'reddit-clone-bf910.firebaseapp.com',
    storageBucket: 'reddit-clone-bf910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaDNzmtkbqxKRJzy6g0h_GQIbfsrB2p4',
    appId: '1:313669347193:android:6e15379c8c0fa507ac31a8',
    messagingSenderId: '313669347193',
    projectId: 'reddit-clone-bf910',
    storageBucket: 'reddit-clone-bf910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaoSShZwZIMCkfC1xX-eauAzieXxnb8MI',
    appId: '1:313669347193:ios:20709f8468cc47a7ac31a8',
    messagingSenderId: '313669347193',
    projectId: 'reddit-clone-bf910',
    storageBucket: 'reddit-clone-bf910.appspot.com',
    iosClientId: '313669347193-p3fsfb9816g3jllc5v8jvlbtq62d5aib.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
